
version: "3.8"
services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa-server
    ports:
      - "9000:9000"
    volumes:
      - .:/medusa
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/medusa-backend
      REDIS_URL: redis://redis:6379
      NODE_ENV: production

  db:
    image: postgres:13
    container_name: medusa-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: medusa-backend
    ports:
      - "5432:5432"
    volumes:
      - medusa-db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: medusa-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  medusa-db-data:
